[package]
name = "tee-pee_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
reqwest = { version = "0.12.9", features = ["blocking", "cookies"] }
scraper = "0.22.0"
serde = { version = "1.0.216", features = ["derive"] }
